PR/Added new workflow for module branch [minor]

diff --git a/workflows/tf-module-branch.yaml b/workflows/tf-module-branch.yaml
--- a/workflows/tf-module-branch.yaml
+++ b/workflows/tf-module-branch.yaml
@@ -1,4 +1,4 @@
-name: Deploy module
+name: Branch CI
 
 on:
   push:
@@ -9,11 +9,46 @@ env:
   GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 
 jobs:
-  check-pr-reay:
+  check-pr-ready:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           fetch_depth: 0
       - run: |
-          echo $(git log -1 --pretty=format:"%s")
+          commit_message=$(git log -1 --pretty=format:"%s")
+          if [[ $commit_message == "WIP/"* ]]; then
+            echo "Not ready to PR yet"
+            exit 0
+          elif [[ $commit_message == "PR/"* ]]; then
+            echo "Ready to create PR!"
+            echo CREATE_PR=true >> $GITHUB_ENV
+            echo SEMVER_BUMP=$(echo $commit_message | awk -F'[\\[\\]]' '{print $2}') >> $GITHUB_ENV
+            echo COMMIT_MESSAGE=$(echo $commit_message | awk -F'[\\/\\[]' '{print $2}') >> $GITHUB_ENV
+            exit 0
+          else
+            echo "Commit message not in required format"
+            exit 1
+          fi
+      - name: Create Pull Request
+        if: env.CREATE_PR == 'true'
+        uses: actions/github-script@v6
+        with:
+          script: |
+            const { repo, owner } = context.repo;
+            const result = await github.rest.pulls.create({
+              title: 'Merge ${{ github.ref_name }} [${{ env.SEMVER_BUMP }}]',
+              owner,
+              repo,
+              head: '${{ github.ref_name }}',
+              base: 'main',
+              body: [
+                '${{ env.COMMIT_MESSAGE }}'
+              ].join('\n')
+            });
+            github.rest.issues.addLabels({
+              owner,
+              repo,
+              issue_number: result.data.number,
+              labels: ['${{ env.SEMVER_BUMP }}']
+            });
