WIP/Added catch for incorrect commit message

diff --git a/.github/workflows/tf-module-branch.yaml b/.github/workflows/tf-module-branch.yaml
--- a/.github/workflows/tf-module-branch.yaml
+++ b/.github/workflows/tf-module-branch.yaml
@@ -17,10 +17,13 @@ jobs:
           fetch_depth: 0
       - run: |
           commit_message=$(git log -1 --pretty=format:"%s")
-          if [[ $commit_message != "PR/*" ]]; then
+          if [[ $commit_message == "WIP/*" ]]; then
             echo "Not ready to PR yet"
             exit 0
           elif [[ $commit_message == "PR/*" ]]; then
             echo "Ready to create PR!"
             exit 0
+          else
+            echo "Commit message not in required format"
+            exit 1
           fi
